-- MySQL Script generated by MySQL Workbench
-- Thu Jun 20 19:30:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rick-and-mort-api
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `rick-and-mort-api` ;

-- -----------------------------------------------------
-- Schema rick-and-mort-api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rick-and-mort-api` DEFAULT CHARACTER SET utf8 ;
USE `rick-and-mort-api` ;

-- -----------------------------------------------------
-- Table `rick-and-mort-api`.`RM_CHARACTER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rick-and-mort-api`.`RM_CHARACTER` ;

CREATE TABLE IF NOT EXISTS `rick-and-mort-api`.`RM_CHARACTER` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NULL,
  `species` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `image` VARCHAR(255) NULL,
  `url` VARCHAR(255) NULL,
  `created` DATETIME NULL,
  `isActive` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rick-and-mort-api`.`LOCATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rick-and-mort-api`.`LOCATION` ;

CREATE TABLE IF NOT EXISTS `rick-and-mort-api`.`LOCATION` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `dimension` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  `created` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rick-and-mort-api`.`EPISODE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rick-and-mort-api`.`EPISODE` ;

CREATE TABLE IF NOT EXISTS `rick-and-mort-api`.`EPISODE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `air_date` VARCHAR(255) NULL,
  `episode` VARCHAR(45) NULL,
  `url` VARCHAR(255) NULL,
  `created` DATETIME NULL,
  `isActive` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rick-and-mort-api`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rick-and-mort-api`.`USER` ;

CREATE TABLE IF NOT EXISTS `rick-and-mort-api`.`USER` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `username` VARCHAR(255) NULL,
  `pass` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rick-and-mort-api`.`ACTIVITY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rick-and-mort-api`.`ACTIVITY` ;

CREATE TABLE IF NOT EXISTS `rick-and-mort-api`.`ACTIVITY` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NULL,
  `action` VARCHAR(45) NULL,
  `entity` VARCHAR(255) NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rick-and-mort-api`.`LOG_ACTIVITY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rick-and-mort-api`.`LOG_ACTIVITY` ;

CREATE TABLE IF NOT EXISTS `rick-and-mort-api`.`LOG_ACTIVITY` (
  `USER_id` INT NOT NULL,
  `ACTIVITY_id` INT NOT NULL,
  PRIMARY KEY (`USER_id`, `ACTIVITY_id`),
  CONSTRAINT `fk_USER_has_ACTIVITY_USER`
    FOREIGN KEY (`USER_id`)
    REFERENCES `rick-and-mort-api`.`USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_has_ACTIVITY_ACTIVITY1`
    FOREIGN KEY (`ACTIVITY_id`)
    REFERENCES `rick-and-mort-api`.`ACTIVITY` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rick-and-mort-api`.`EPISODE_CHARACTER_RELATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rick-and-mort-api`.`EPISODE_CHARACTER_RELATION` ;

CREATE TABLE IF NOT EXISTS `rick-and-mort-api`.`EPISODE_CHARACTER_RELATION` (
  `EPISODE_id` INT NOT NULL,
  `RM_CHARACTER_id` INT NOT NULL,
  PRIMARY KEY (`EPISODE_id`, `RM_CHARACTER_id`),
  CONSTRAINT `fk_EPISODE_has_RM_CHARACTER_EPISODE1`
    FOREIGN KEY (`EPISODE_id`)
    REFERENCES `rick-and-mort-api`.`EPISODE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EPISODE_has_RM_CHARACTER_RM_CHARACTER1`
    FOREIGN KEY (`RM_CHARACTER_id`)
    REFERENCES `rick-and-mort-api`.`RM_CHARACTER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
